### ISSUE TITLE
Create 'repository_dependencies.xml' files for 2 workflows.

### ISSUE THREAD

**Issue by DiDigsDNA** [Public-Health-Bioinformatics/flu_classification_suite#4]
`flu_classification_suite/workflows/assign_clades_and_extract_antigenic_maps` has a file called  `repository_dependencies.xml` file but the corresponding folders in  `assign_clades_extract_antigenic_sites_output_to_line_list` and `assign_clades_extract_antigenic_sites_output_to_aggregated_line_list` don't so it needs to be added.
I will assign it to myself and do it.

**Comment by DiDigsDNA** [comment]
`repository_dependencies.xml` files are now present in `flu_classification_suite/workflows/assign_clades_extract_antigenic_sites_output_to_line_list` and `flu_classification_suite/workflows/assign_clades_extract_antigenic_sites_output_to_aggregated_line_list`

Dan can you please review.

**Comment by dfornika** [comment]
@dfornika
